CREATE DATABASE IF NOT EXISTS 'livraria';

USE 'livraria';

CREATE TABLE IF NOT EXISTS 'livro' (
  'ID' int(11) NOT NULL AUTO_INCREMENT,
  'TITULO' varchar(200) DEFAULT NULL,
  'DESCRICAO' varchar(400) DEFAULT NULL,
  'AUTOR' varchar(400) DEFAULT NULL,
  PRIMARY KEY ('ID'),
  UNIQUE KEY 'ID_UNIQUE' ('ID')
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;